//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModupDAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ModupEntities : DbContext
    {
        public ModupEntities()
            : base("name=ModupEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<tbAnswer> tbAnswers { get; set; }
        public virtual DbSet<tbAwardedModule> tbAwardedModules { get; set; }
        public virtual DbSet<tbAwardedProj> tbAwardedProjs { get; set; }
        public virtual DbSet<tbCheckpointReq> tbCheckpointReqs { get; set; }
        public virtual DbSet<tbClient> tbClients { get; set; }
        public virtual DbSet<tbDeveloper> tbDevelopers { get; set; }
        public virtual DbSet<tbEducation> tbEducations { get; set; }
        public virtual DbSet<tbEvaluation> tbEvaluations { get; set; }
        public virtual DbSet<tbExperience> tbExperiences { get; set; }
        public virtual DbSet<tbMessage> tbMessages { get; set; }
        public virtual DbSet<tbModCheckpoint> tbModCheckpoints { get; set; }
        public virtual DbSet<tbModMessage> tbModMessages { get; set; }
        public virtual DbSet<tbModRequest> tbModRequests { get; set; }
        public virtual DbSet<tbModule> tbModules { get; set; }
        public virtual DbSet<tbModuleWorkroom> tbModuleWorkrooms { get; set; }
        public virtual DbSet<tbModWorkroomFile> tbModWorkroomFiles { get; set; }
        public virtual DbSet<tbPM> tbPMs { get; set; }
        public virtual DbSet<tbPortfolio> tbPortfolios { get; set; }
        public virtual DbSet<tbProject> tbProjects { get; set; }
        public virtual DbSet<tbProjProposal> tbProjProposals { get; set; }
        public virtual DbSet<tbProjWorkroom> tbProjWorkrooms { get; set; }
        public virtual DbSet<tbProjWorkroomFile> tbProjWorkroomFiles { get; set; }
        public virtual DbSet<tbProposal> tbProposals { get; set; }
        public virtual DbSet<tbQualityAssurance> tbQualityAssurances { get; set; }
        public virtual DbSet<tbQuestion> tbQuestions { get; set; }
        public virtual DbSet<tbRequirementEngineer> tbRequirementEngineers { get; set; }
        public virtual DbSet<tbSkill> tbSkills { get; set; }
        public virtual DbSet<tbSubModule> tbSubModules { get; set; }
        public virtual DbSet<tbUser> tbUsers { get; set; }
        public virtual DbSet<tbUserCredential> tbUserCredentials { get; set; }
    }
}
