//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModupDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbCheckpointReq
    {
        public int reqID { get; set; }
        public int chkID { get; set; }
        public string title { get; set; }
        public string date { get; set; }
        public string files { get; set; }
        public string status { get; set; }
    
        public virtual tbModCheckpoint tbModCheckpoint { get; set; }
    }
}
