//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModupDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbDeveloper
    {
        public tbDeveloper()
        {
            this.tbAwardedModules = new HashSet<tbAwardedModule>();
            this.tbEvaluations = new HashSet<tbEvaluation>();
            this.tbPortfolios = new HashSet<tbPortfolio>();
            this.tbProposals = new HashSet<tbProposal>();
            this.tbSkills = new HashSet<tbSkill>();
        }
    
        public int clientID { get; set; }
        public int devID { get; set; }
        public string affiliation { get; set; }
    
        public virtual ICollection<tbAwardedModule> tbAwardedModules { get; set; }
        public virtual tbClient tbClient { get; set; }
        public virtual ICollection<tbEvaluation> tbEvaluations { get; set; }
        public virtual ICollection<tbPortfolio> tbPortfolios { get; set; }
        public virtual ICollection<tbProposal> tbProposals { get; set; }
        public virtual ICollection<tbSkill> tbSkills { get; set; }
    }
}
