//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModupDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbEvaluation
    {
        public tbEvaluation()
        {
            this.tbQuestions = new HashSet<tbQuestion>();
        }
    
        public int evalID { get; set; }
        public int devID { get; set; }
        public string skill { get; set; }
        public string date { get; set; }
        public string result { get; set; }
        public Nullable<double> score { get; set; }
    
        public virtual tbDeveloper tbDeveloper { get; set; }
        public virtual ICollection<tbQuestion> tbQuestions { get; set; }
    }
}
