//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModupDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbModCheckpoint
    {
        public tbModCheckpoint()
        {
            this.tbCheckpointReqs = new HashSet<tbCheckpointReq>();
        }
    
        public int chkID { get; set; }
        public int wrID { get; set; }
        public string title { get; set; }
        public string dueDate { get; set; }
        public string status { get; set; }
        public string end { get; set; }
        public string description { get; set; }
    
        public virtual ICollection<tbCheckpointReq> tbCheckpointReqs { get; set; }
        public virtual tbModuleWorkroom tbModuleWorkroom { get; set; }
    }
}
