//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModupDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbModuleWorkroom
    {
        public tbModuleWorkroom()
        {
            this.tbModCheckpoints = new HashSet<tbModCheckpoint>();
            this.tbModMessages = new HashSet<tbModMessage>();
            this.tbModRequests = new HashSet<tbModRequest>();
            this.tbModWorkroomFiles = new HashSet<tbModWorkroomFile>();
        }
    
        public int wrID { get; set; }
        public int modID { get; set; }
    
        public virtual tbAwardedModule tbAwardedModule { get; set; }
        public virtual ICollection<tbModCheckpoint> tbModCheckpoints { get; set; }
        public virtual ICollection<tbModMessage> tbModMessages { get; set; }
        public virtual ICollection<tbModRequest> tbModRequests { get; set; }
        public virtual ICollection<tbModWorkroomFile> tbModWorkroomFiles { get; set; }
    }
}
