//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModupDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbPM
    {
        public tbPM()
        {
            this.tbProjects = new HashSet<tbProject>();
        }
    
        public int pmID { get; set; }
        public int userID { get; set; }
        public string totalSpending { get; set; }
        public string awardedProj { get; set; }
    
        public virtual tbUser tbUser { get; set; }
        public virtual ICollection<tbProject> tbProjects { get; set; }
    }
}
