//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModupDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbProjProposal
    {
        public tbProjProposal()
        {
            this.tbAwardedProjs = new HashSet<tbAwardedProj>();
        }
    
        public int prjpropID { get; set; }
        public int raID { get; set; }
        public int projID { get; set; }
        public string bidAmt { get; set; }
        public string coverLetter { get; set; }
        public string estCompletion { get; set; }
    
        public virtual ICollection<tbAwardedProj> tbAwardedProjs { get; set; }
        public virtual tbProject tbProject { get; set; }
        public virtual tbRequirementEngineer tbRequirementEngineer { get; set; }
    }
}
