//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modupv1
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbAwardedModule
    {
        public tbAwardedModule()
        {
            this.tbModuleWorkrooms = new HashSet<tbModuleWorkroom>();
        }
    
        public int devID { get; set; }
        public int modID { get; set; }
        public int propID { get; set; }
        public string status { get; set; }
    
        public virtual tbDeveloper tbDeveloper { get; set; }
        public virtual tbModule tbModule { get; set; }
        public virtual tbProposal tbProposal { get; set; }
        public virtual ICollection<tbModuleWorkroom> tbModuleWorkrooms { get; set; }
    }
}
