//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modupv1
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbMessage
    {
        public int mID { get; set; }
        public int wrID { get; set; }
        public string mfrom { get; set; }
        public string mto { get; set; }
        public string text { get; set; }
        public string dateTime { get; set; }
        public string attachment { get; set; }
    
        public virtual tbProjWorkroom tbProjWorkroom { get; set; }
    }
}
