//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modupv1
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbProject
    {
        public tbProject()
        {
            this.tbModules = new HashSet<tbModule>();
            this.tbProjProposals = new HashSet<tbProjProposal>();
        }
    
        public int projID { get; set; }
        public int pmID { get; set; }
        public string moduleNo { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public string postDate { get; set; }
        public string closeDate { get; set; }
        public string status { get; set; }
        public Nullable<short> estimatedAmt { get; set; }
        public string fileName { get; set; }
        public string technology { get; set; }
    
        public virtual tbAwardedProj tbAwardedProj { get; set; }
        public virtual ICollection<tbModule> tbModules { get; set; }
        public virtual tbPM tbPM { get; set; }
        public virtual ICollection<tbProjProposal> tbProjProposals { get; set; }
    }
}
