//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modupv1
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbProjWorkroomFile
    {
        public int fileID { get; set; }
        public int wrID { get; set; }
        public string filename { get; set; }
        public string date { get; set; }
        public string uploadedBy { get; set; }
        public string size { get; set; }
    
        public virtual tbProjWorkroom tbProjWorkroom { get; set; }
    }
}
