//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modupv1
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbSkill
    {
        public int skillID { get; set; }
        public int devID { get; set; }
        public string name { get; set; }
        public string skillLevel { get; set; }
        public string type { get; set; }
        public string hourlyRate { get; set; }
    
        public virtual tbDeveloper tbDeveloper { get; set; }
    }
}
